#Configuración de BD WorkBench :3

#Configuración del servidor
server.port=8080
spring.application.name=vitalium

#Configuración de la BD
spring.datasource.url=jdbc:mysql://localhost:3306/vitalium?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
sping.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jap.properties.hibernate.format_sql=true

#Loggin
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.modularminds.vittalium=DEBUG

# Google OAuth2 - Tu CLIENT_ID obtenido del paso 1
google.client-id=377149430777-bjvj9pe3p1lcrf1cjnn1if6r2967cmr5.apps.googleusercontent.com

spring.security.oauth2.client.registration.facebook.client-id=25655861484114587
spring.security.oauth2.client.registration.facebook.client-secret=8f8e29df4e738ad562b19d17b8511992
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/login/oauth2/code/facebook
spring.security.oauth2.client.registration.facebook.client-name=Facebook

spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v18.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v18.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,first_name,last_name,picture
spring.security.oauth2.client.provider.facebook.user-name-attribute=id
